[package]
name = "rstat"
description = "Probability distributions and statistics in Rust with integrated fitting routines, convolution support and mixtures"

version = "0.3.0"
authors = ["Tom Spooner <spooner10000@gmail.com>"]

license = "MIT"
readme = "README.md"

keywords = ["probability", "statistics", "sampling", "distribution"]

repository = "https://github.com/tspooner/rstat"
documentation = "https://docs.rs/rstat"

edition = "2018"

[dependencies]
rand = "0.7"
rand_distr = "0.2"

spaces = "5.0"
ndarray = "0.12"
ndarray-linalg = "0.11"
special-fun = "0.2"

[dev-dependencies]
ndarray-linalg = { version = "0.11", features = ["openblas"] }
