[package]
name = "rstat"
description = "Probability distributions and statistics in Rust with integrated fitting routines, convolution support and mixtures"

version = "0.3.0"
authors = ["Tom Spooner <spooner10000@gmail.com>"]

license = "MIT"
readme = "README.md"

keywords = ["probability", "statistics", "sampling", "distribution"]

repository = "https://github.com/tspooner/rstat"
documentation = "https://docs.rs/rstat"

edition = "2018"

[features]
default = []

backend = ["ndarray-linalg"]

[dependencies]
failure = "0.1"

rand = "0.7"
rand_distr = "0.2"

num = "0.2"
spaces = "5.0"
special-fun = "0.2"

ndarray = "0.13"
ndarray-linalg = { version = "0.12", optional = true }

[dev-dependencies]
ndarray-linalg = { version = "0.12", features = ["openblas"] }
